/* Generated by generate_course.py. */
#define COURSE_BANDS 41
#define COURSE_BANK 12
#define EVENT_PROJECT_OFFSET 192
#define EVENT_PROJECT_COUNT 16
/* Records: signed center x, ground y, road half-width, hill clip bottom. */
static const u16 event_depth[16]={28,32,36,42,50,60,72,86,102,124,150,184,230,292,380,512};
static const unsigned char band_y[41]={64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,110,114,118,122,126,130,134,138,142,146,150,154,158,162,166,170,174,178,182};
static const unsigned char band_h[41]={2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4};
