/* Generated by tools/generate_assets.py. RGB components are 0..31. */
#ifndef RALLY_PALETTE_H
#define RALLY_PALETTE_H

#define COL_TRANSPARENT 0
#define COL_SKY 1
#define COL_SKY_LIGHT 2
#define COL_DISTANT 3
#define COL_MOUNTAIN 4
#define COL_GRASS 5
#define COL_TREE 6
#define COL_GRASS_DARK 7
#define COL_RUST 8
#define COL_ROAD 9
#define COL_ROAD_LIGHT 10
#define COL_VERGE 11
#define COL_DARK 12
#define COL_ORANGE 13
#define COL_METAL 14
#define COL_WHITE 15
#define COL_GRASS_ALT COL_GRASS_DARK

static const unsigned char v9990_palette[48] = {
     0,  0,  0, /*  0 TRANSPARENT */
    12, 23, 29, /*  1 SKY */
    20, 27, 28, /*  2 SKY_LIGHT */
    13, 19, 21, /*  3 DISTANT */
     7, 13, 14, /*  4 MOUNTAIN */
    16, 22,  9, /*  5 GRASS */
     4,  9,  7, /*  6 TREE */
    13, 18,  8, /*  7 GRASS_DARK */
    21, 10,  6, /*  8 RUST */
    22, 19, 13, /*  9 ROAD */
    24, 21, 15, /* 10 ROAD_LIGHT */
    27, 25, 19, /* 11 VERGE */
     4,  5,  5, /* 12 DARK */
    29, 18,  8, /* 13 ORANGE */
    17, 19, 17, /* 14 METAL */
    30, 29, 25, /* 15 WHITE */
};

#endif
